// Shapes shared across the page. moves.json is generated by tools/export_moves.py from prompts/site_prompts.py
// and holds only names, descriptions and examples; the prompts themselves stay on the server.

export type ModeId = 'image' | 'ideas'
export type Engine = 'gemini' | 'groq'
export type Provider = 'gemini' | 'groq' | 'claude' | 'openai'
export type Evidence = 'strong' | 'mixed' | 'drifts'

export interface MoveField {
  name: string
  label: string
  max: number
  placeholder?: string
  optional?: boolean
}

export interface MoveDef {
  id: string
  group: string
  label: Record<ModeId, string>
  blurb: Record<ModeId, string>
  example: Record<ModeId, string>
  count: number
  inputs?: 1 | 2            // 2 = a collision: needs two boxes
  field?: MoveField         // a second box typed by the visitor (Domain transfer's target, …)
  field2?: MoveField
  diff?: boolean
  stackable?: boolean
  evidence?: Evidence       // how the move did in the studio's tests
  evidenceNote?: string
  deck?: boolean            // Oblique Strategies: the server draws a card and returns it with the results
}

export interface ModeDef { label: string; placeholder: string; anchor: string }

export interface MovesFile {
  exported: string
  default_mode: ModeId
  modes: Record<ModeId, ModeDef>
  groups: string[]
  stack_max: number
  moves: MoveDef[]
}

// ── the map ──
export interface ConceptBox {
  id: string
  kind: 'concept'
  parent: string | null      // the transform that made it, or null for a typed concept
  rank: number | null        // its place among its transform's results (0 = best)
  text: string               // as returned, with any leading [tag]
  plain: string              // without the tag
  tag: string
  x?: number
  y?: number
  time: number
  verdict?: 'kept' | 'discarded'
}

export interface SourceBox {
  id: string
  kind: 'source'
  parent: null
  text: string
  plain: string
  title: string
  x?: number
  y?: number
  time: number
}

export interface TransformBox {
  id: string
  kind: 'transform'
  parent: string             // the concept it was applied to (for a collision: the first box)
  parent2?: string           // a collision's second box
  move: string               // label as shown
  moveIds: string[]          // one id, or several for a stack
  field: string
  field2?: string
  mode: ModeId
  words: number
  engine: string
  note: string
  status: 'working' | 'done' | 'error'
  error: string
  shown: number              // which result is on the map
  x?: number
  y?: number
  time: number
}

export type MapBox = ConceptBox | SourceBox | TransformBox

export interface Graph {
  v: 3
  nodes: Record<string, MapBox>
  order: string[]
  selected: string | null
}
