// Shapes shared across the page. moves.json is generated by tools/export_moves.py from prompts/site_prompts.py
// and holds only names, descriptions and examples; the prompts themselves stay on the server.

export type ModeId = 'image' | 'ideas'
export type Engine = 'gemini' | 'groq'
export type Provider = 'gemini' | 'groq' | 'claude' | 'openai'
export type Evidence = 'strong' | 'mixed' | 'drifts'

export interface MoveField {
  name: string
  label: string
  max: number
  placeholder?: string
  optional?: boolean
}

export interface MoveDef {
  id: string
  group: string
  label: Record<ModeId, string>
  blurb: Record<ModeId, string>
  example: Record<ModeId, string>
  count: number
  inputs?: 1 | 2            // 2 = a collision: needs two boxes
  field?: MoveField         // a second box typed by the visitor (Domain transfer's target, …)
  field2?: MoveField
  diff?: boolean
  stackable?: boolean
  evidence?: Evidence       // how the move did in the studio's tests
  evidenceNote?: string
  deck?: boolean            // Oblique Strategies: the server draws a card and returns it with the results
}

export interface ModeDef { label: string; placeholder: string; anchor: string }

export interface MovesFile {
  exported: string
  default_mode: ModeId
  modes: Record<ModeId, ModeDef>
  groups: string[]
  stack_max: number
  moves: MoveDef[]
}

// ── the map (version 4: a node graph) ──
// Concepts and sources are typed in; a transform applies one move to the node(s) wired into it and keeps its own
// results. Whichever result is showing is the transform's output, which can be wired into the next transform.
// Nothing runs until the visitor presses Run. A transform whose inputs or settings changed since it ran is stale.

export type Verdict = 'kept' | 'discarded'

interface NodeBase {
  id: string
  x: number
  y: number
  time: number
}

export interface ConceptBox extends NodeBase {
  kind: 'concept'
  text: string
}

export interface SourceBox extends NodeBase {
  kind: 'source'
  text: string               // a pasted passage; only collisions take it
}

export interface NoteBox extends NodeBase {
  kind: 'note'
  text: string               // a sticky note: never sent anywhere
}

export interface Result {
  text: string               // as returned, with any leading [tag]
  plain: string              // without the tag
  tag: string
  verdict?: Verdict
}

export interface TransformBox extends NodeBase {
  kind: 'transform'
  moveIds: string[]          // one move (older maps may hold a stack of two or three)
  inputs: (string | null)[]  // wired nodes, one per input port (two for a collision)
  field: string              // the move's extra boxes (target domain, rule, ...)
  field2: string
  mode: ModeId
  words: number              // 0 = the mode's default length
  results: Result[]
  shown: number              // which result is the output
  status: 'idle' | 'working' | 'error'
  error: string
  engine: string             // who answered the last run
  note: string               // a note from the relay (e.g. which free engine answered)
  card: string               // Oblique Strategies: the card drawn on the last run
  ranKey: string             // inputs and settings at the last successful run; differs = stale
  bypass?: boolean           // passes its first input straight through
}

export type MapBox = ConceptBox | SourceBox | NoteBox | TransformBox

export interface Graph {
  v: 4
  nodes: Record<string, MapBox>
  order: string[]
  selected: string | null
}
